package view.request;

public enum RequestType {

    HELP,
    EXIT,
    INVALID_COMMAND,
    DEATH_MATCH,
    CAPTURE_FLAG1,
    CAPTURE_FLAG2,
    SHOW_GAME_INFO,
    SHOW_MY_MINIONS,
    SHOW_OPPONENT_MINIONS,
    SHOW_CARD_INFO,
    SELECT_CARD,
    MOVE_CARD,
    ATTACK_TO_OPPONENT,
    COMBO_ATTACK,
    USE_SPECIAL_POWER,
    SHOW_MY_HAND,
    INSERT_CARD_FROM_HAND_TO_MAP,
    SHOW_COLLECTABLES,
    END_TURN,
    SHOW_SELECTED_ITEM_INFO,
    USE_COllectable_ITEM,
    ENTER_GRAVEYARD,
    SHOW_NEXT_CARD,
    SHOW_CARD_INFO_IN_GRAVEYARD,
    SHOW_ALL_CARDS_IN_GRAVEYARD,
    END_GAME,
    SHOW_MENU,

}
