package models;

public enum RequestType {
    EXIT,
    HELP,
    SAVE,
    LOGIN,
    LOGOUT,
    SIGN_UP,
    SHOW_LEADERBOARD,
    ENTER_BATTLE,
    ENTER_SHOP,
    ENTER_COLLECTION,
    SHOW_COLLECTION_CARDS,
    SEARCH_IN_COLLECTION,
    CREATE_DECK,
    DELETE_DECK,
    ADD_CARD_TO_DECK,
    REMOVE_CARD_FROM_DECK,
    VALIDATE_DECK,
    SELECT_MAIN_DECK,
    SHOW_ALL_DECKS,
    SHOW_DECK,
    SHOW_SHOP_CARDS,
    SELL_CARD,
    BUY_CARD,
    SEARCH_IN_SHOP,
    SINGLE_PLAYER,
    MULTI_PLAYER,
    DEATH_MATCH,
    CAPTURE_FLAG1,
    CAPTURE_FLAG2,
    SELECT_SECOND_PLAYER,
    STORY_GAME,



}
